version: '2'
services:
  frontend:
    build:
      context: ./twentyyear/
      dockerfile: Dockerfile
    image: nuxt:latest
    container_name: nuxt_twentyyear
    ports:
      - 80:80
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 80
  demo:
    restart: always
    image: nginx:1.16.1-alpine
    ports: 
      - 8080:80
    volumes:
      - ./demo/dist/:/usr/share/nginx/html/
      - ./demo/nginx/default.conf:/etc/nginx/conf.d/default.conf